---
- name: Install and configure Apache web server
  hosts: web-servers
  become: true

  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Enable Apache service
      systemd:
        name: apache2
        enabled: true
        state: started
