---
- name: MYSQL სერვერის ინსტალაცია
  hosts: db-servers
  become: yes

  vars:
    mysql_repo_url: "https://repo.mysql.com/mysql-apt-config_0.8.23-1_all.deb"
    mysql_root_password: "12345678"

  tasks:
    - name: MYSQL რეპოზიტორიის გადმოწერა
      get_url:
        url: "{{mysql_repo_url}}"
        dest: "/tmp/mysql-apt-config.deb"
        mode: 0644

    - name: MYSQL რეპოზიტორიის ინსტალაცია
      apt:
        deb: "/tmp/mysql-apt-config.deb"
        update_cache: yes

    - name: MYSQL სერვერის ინსტალაცია
      apt:
        name:
          - mysql-server

    - name: MYSQL root მომხმარებლის პაროლის ცვლილება
      debconf:
        name: mysql-server-8.0
        question: "mysql-server-8.0 mysql-server/root_password password {{mysql_root_password}}"
        vtype: password
        value: "{{mysql_root_password}}"
      notify: Restart MySQL Service

    - name: MYSQL პაროლის დადასტურება
      debconf:
        name: mysql-server-8.0
        question: "mysql-server-8.0 mysql-server/root_password_again password {{mysql_root_password}}"
        value: "{{mysql_root_password}}"
        vtype: password

  handlers:
    - name: Restart MySQL Service
      service:
        name: mysql
        state: restarted
