---
- name: Install multiple packages
  hosts: web1
  become: true
  tasks:
    - name: Install the latest version of sudo package
      yum:
        name: sudo
        state: latest

    - name: Downgrade vsftpd to version 2.2.2
      yum:
        name: vsftpd-2.2.2
        state: present
        allow_downgrade: yes
