---
- name: Install wget package
  hosts: web1
  become: true
  tasks:
    - name: Download wget RPM package
      get_url:
        url: http://mirror.centos.org/centos/7/os/x86_64/Packages/wget-1.14-18.el7_6.1.x86_64.rpm
        dest: /tmp/wget.rpm

    - name: Install wget RPM package
      yum:
        name: /tmp/wget.rpm
        state: present
